spring.application.name=cyclemart-be-remake
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/cyclemart_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


momo.partnerCode=MOMO
momo.accessKey=F8BBA842ECF85
momo.secretKey=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.returnUrl=http://localhost:5174/payment-success
momo.ipnUrl=http://localhost:8080/api/v1/payments/momo/ipn

#chua lam
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=iwakeupwhen@gmail.com
spring.mail.password=dghy zgeq vuov yyom
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App Configuration
app.name=CycleMart
app.payment.mock=false